module.exports = {
    myprofile: getMyprofile()
};


function getMyprofile() {
    return{
        "code": 0,
        "status": "okay",
        "user": {
            "id": 1487,
            "emailid": "qwesujit.dumbfe@gmail.com",
            "profile_complete": 0,
            "profile_id": "LB1487",
            "firstname": "aradhya",
            "middlename": " fyuyg",
            "lastname": "Sfg",
            "gender": "Male",
            "marital_status": "Unmarried",
            "birth_date": "1982-05-20",
            "degree": "B>E",
            "show_details": "No",
            "age": 32,
            "birth_time": "12:34 AM",
            "birth_place": "asfasdf",
            "caste": "Brahmin- Saraswat",
            "current_place_residence": "Latur",
            "height": "27",
            "weight": 0,
            "mobile": 3243789870,
            "physic": "",
            "complexion": "",
            "physical_disablity": "",
            "physical_disablity_specify": "",
            "spects": "",
            "blood_group": "",
            "diet": "",
            "fathername": "nmhah",
            "mothername": "gygty",
            "father_occupation": "hhjhbj",
            "mother_occupation": "ghg",
            "brothers": "ghg",
            "sisters": "bvhjg",
            "family_wealth": "",
            "native_atpost": "",
            "native_taluka": "",
            "native_dist": "",
            "mamaname": "gikhgol",
            "relatives": "huh",
            "education": "M.Arch",
            "experience": "",
            "more_edu_info": "afdsfd",
            "occupation": "Service",
            "occupation_details": "Commercial Pilot",
            "occupation_info": "asdfasdf",
            "income": "",
            "gotra": "fgyutg",
            "devak": "tgiy",
            "rashi": "tgiyi",
            "nakshatra": "tyti",
            "gan": "",
            "nadi": "",
            "charan": "",
            "mangal": "",
            "exp_education": "",
            "exp_height_maxi": "",
            "exp_height_mini": "",
            "age_diff_maxi": 0,
            "age_diff_mini": 0,
            "exp_complexion": "",
            "exp_spects": "",
            "exp_personality": "",
            "exp_location": "",
            "exp_occupation": "",
            "exp_income": "",
            "exp_mangal": "",
            "imagename": "",
            "extention": "",
            "delete_account": "",
            "delete_reason": "",
            "delete_comment": "",
            "email_unsubscribe": 0,
            "credits_remaining": 0,
            "credits_used": 0,
            "edu_level": "",
            "edu_field": "",
            "working_with": "",
            "created_date": "2014-06-09T18:00:52Z",
            "update_date": "2014-06-09T18:00:52Z",
            "last_loggedin": "2014-06-09T18:00:52Z"
        }
    }
}