module.exports = {
    profile: view_profile()
};


function view_profile() {
    return{
            "id": 1488,
            "profile_complete": 0,
            "profile_id": "LB1488",
            "firstname": "Admin",
            "middlename": "guhgyu",
            "lastname": "manager",
             "phone": "1234567890",
            "gender": "Male",
            "marital_status": "Unmarried",
            "birth_date": "1982-05-20",
            "show_details": "No",
            "age": 32,
            "birth_time": "12:34 AM",
            "birth_place": "asfasdf",
            "caste": "96k Maratha",
            "current_place_residence": "Pune",
            "height": 150,
            "weight": 70,
            "physic": "slim",
            "complexion": "medium",
            "physical_disablity": "No",
            "physical_disablity_specify": "",
            "spects": "",
            "blood_group": "o+",
            "diet": "",
            "fathername": "aaa",
            "mothername": "bbb",
            "father_occupation": "teacher",
            "mother_occupation": "housewife",
            "brothers": "vishal",
            "sisters": "mayuri",
            "family_wealth": "",
            "native_atpost": "loni",
            "native_taluka": "rahata",
            "native_dist": "anagar",
            "mamaname": "aher",
            "relatives": "waghe",
            "education": "B.A",
            "education_level": "bachlor",
            "education_field": "arts",
            "experience": "",
            "more_edu_info": "afdsfd",
            "occupation": "Service",
            "occupation_details": "Commercial Pilot",
            "occupation_info": "asdfasdf",
            "income": "2 lakh",
            "gotra": "adf",
            "devak": "ggug",
            "rashi": "tul",
            "nakshatra": "guyugy",
            "gan": "mnushya",
            "nadi": "madhya",
            "charan": "1",
            "mangal": "No",
            "exp_education": "",
            "exp_height_maxi": "",
            "exp_height_mini": "",
            "age_diff_maxi": 0,
            "age_diff_mini": 0,
            "exp_complexion": "",
            "exp_spects": "",
            "exp_personality": "",
            "exp_location": "",
            "exp_occupation": "",
            "exp_income": "",
            "exp_mangal": "",
            "imagename": "",
            "extention": "",
            "delete_account": "",
            "delete_reason": "",
            "delete_comment": "",
            "email_unsubscribe": 0,
            "credits_remaining": 0,
            "credits_used": 0,
            "edu_level": "",
            "edu_field": "",
            "working_with": "",
            "created_date": "2014-06-18T01:58:49Z",
            "update_date": "2014-06-18T01:58:49Z",
            "last_loggedin": "2014-06-18T01:58:49Z"
        }

}
